name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          args: '--frozen-lockfile'
      - run: pnpm run lint
      - run: pnpm run prettier:check
      - run: pnpm run test:unit
      - run: pnpm run test:integration
      - run: pnpm run test:e2e
      - run: pnpm run build:release

